# Generated by Django 3.1.3 on 2020-11-21 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateField(default=datetime.datetime(2020, 11, 21, 15, 41, 22, 102996))),
                ('sale_or_rent', models.CharField(choices=[('sale', 'Продажба'), ('rent', 'Наем')], max_length=100)),
                ('district', models.CharField(choices=[('Благоевград град', 'Благоевград град'), ('Благоевград област', 'Благоевград област')], max_length=100)),
                ('city', models.CharField(choices=[('Благоевград', 'Благоевград'), ('Дупница', 'Дупница'), ('Симитли', 'Симитли')], max_length=100)),
                ('area', models.CharField(choices=[('Център', 'Център'), ('Струмско', 'Струмско'), ('Гарата', 'Гарата')], max_length=100)),
                ('type', models.CharField(choices=[('Апартамент', 'Апартамент'), ('Къща', 'Къща'), ('Етаж от къща', 'Етаж от къща')], max_length=100)),
                ('price', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('construction', models.CharField(choices=[('Тухла', 'Тухла'), ('Панел', 'Панел'), ('ЕПК', 'ЕПК'), ('Гредоред', 'Гредоред')], max_length=100)),
                ('image_one', models.ImageField(blank=True, upload_to='images')),
                ('image_two', models.ImageField(blank=True, upload_to='images')),
                ('image_three', models.ImageField(blank=True, upload_to='images')),
                ('image_four', models.ImageField(blank=True, upload_to='images')),
                ('image_five', models.ImageField(blank=True, upload_to='images')),
                ('image_six', models.ImageField(blank=True, upload_to='images')),
                ('image_seven', models.ImageField(blank=True, upload_to='images')),
                ('image_eight', models.ImageField(blank=True, upload_to='images')),
                ('image_nine', models.ImageField(blank=True, upload_to='images')),
                ('image_ten', models.ImageField(blank=True, upload_to='images')),
                ('number_rooms', models.CharField(choices=[('1-стаен', '1-стаен'), ('2-стаен', '2-стаен'), ('3-стаен', '3-стаен'), ('4-стаен', '4-стаен'), ('Многостаен', 'Многостаен')], max_length=100)),
                ('furniture', models.CharField(choices=[('Обзаведен', 'Обзаведен'), ('Полуобзаведен', 'Полуобзаведен'), ('Необзаведен', 'Необзаведен')], max_length=100)),
                ('elevator', models.CharField(choices=[('Да', 'Да'), ('Не', 'Не')], default='Не', max_length=100)),
                ('built_date', models.CharField(blank=True, max_length=4)),
                ('description', models.TextField()),
                ('top_offer', models.BooleanField(default=False)),
                ('counter_seen', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Всички', 'Всички'), ('Апартамент', 'Апартамент'), ('Къща', 'Къща'), ('Етаж от къща', 'Етаж от къща')], default=('Всички', 'Всички'), max_length=100)),
                ('number_rooms', models.CharField(choices=[('Всички', 'Всички'), ('1-стаен', '1-стаен'), ('2-стаен', '2-стаен'), ('3-стаен', '3-стаен'), ('4-стаен', '4-стаен'), ('Многостаен', 'Многостаен')], default=('Всички', 'Всички'), max_length=100)),
                ('sort', models.CharField(choices=[('Цена Възходяща', 'Цена Възходяща'), ('Цена Низходяща', 'Цена Низходяща'), ('Най-нови', 'Най-нови'), ('Най-гледани', 'Най-гледани')], default=('Цена Възходяща', 'Цена Възходяща'), max_length=100)),
            ],
        ),
    ]
