# Generated by Django 3.1.3 on 2020-11-21 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_ad_additionalfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfilter',
            name='sale_or_rent',
            field=models.CharField(choices=[('Продажба', 'Продажба'), ('Наем', 'Наем')], default=('Продажба', 'Продажба'), max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 18, 23, 25, 708402)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sale_or_rent',
            field=models.CharField(choices=[('Продажба', 'Продажба'), ('Наем', 'Наем')], max_length=100),
        ),
    ]
