# Generated by Django 3.1.3 on 2020-11-22 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0003_auto_20201121_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 11, 47, 2, 258164)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='district',
            field=models.CharField(choices=[('област Благоевград', 'област Благоевград'), ('област Кюстендил', 'област Кюстендил')], max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='sort',
            field=models.CharField(choices=[('---', '---'), ('Топ оферти', 'Топ оферти'), ('Цена Възходяща', 'Цена Възходяща'), ('Цена Низходяща', 'Цена Низходяща'), ('Най-нови', 'Най-нови'), ('Най-гледани', 'Най-гледани')], default=('---', '---'), max_length=100),
        ),
    ]
