# Generated by Django 3.1.3 on 2020-11-22 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_auto_20201122_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfilter',
            name='sale_or_rent',
        ),
        migrations.AddField(
            model_name='additionalfilter',
            name='purpose',
            field=models.CharField(choices=[('Всички', 'Всички'), ('Продажба', 'Продажба'), ('Наем', 'Наем')], default=('Всички', 'Всички'), max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 12, 9, 44, 910826)),
        ),
    ]
