# Generated by Django 3.1.3 on 2020-11-25 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0006_auto_20201122_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='area',
            field=models.CharField(choices=[('Център', 'Център'), ('Струмско', 'Струмско'), ('Грамада', 'Грамада')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 10, 4, 20, 252324)),
        ),
    ]
