# Generated by Django 3.1.3 on 2020-11-25 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_app', '0007_auto_20201125_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 25, 11, 13, 30, 437810)),
        ),
    ]
