# Generated by Django 3.1.3 on 2020-11-26 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0010_auto_20201126_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookingfor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 26, 17, 37, 46, 148647)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 11, 26, 17, 37, 46, 148647)),
        ),
    ]
