# Generated by Django 3.1.3 on 2020-12-02 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0011_auto_20201126_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfilter',
            name='my_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 20, 30, 31, 745347)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 20, 30, 31, 745347)),
        ),
    ]
