# Generated by Django 3.1.3 on 2020-12-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0012_auto_20201202_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfilter',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 12, 8, 13, 372830)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 12, 8, 13, 383793)),
        ),
    ]
