# Generated by Django 3.1.3 on 2020-12-04 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0014_auto_20201204_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 4, 11, 58, 4, 797460)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 4, 11, 58, 4, 804492)),
        ),
    ]
