# Generated by Django 3.1.3 on 2020-12-05 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0016_auto_20201205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.districtcityarea'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.districtcity'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 12, 7, 122410)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 12, 7, 122410)),
        ),
    ]
