# Generated by Django 3.1.3 on 2020-12-05 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0018_auto_20201205_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 38, 44, 766355)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type_premise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.typepremise'),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.typepremise'),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 38, 44, 766355)),
        ),
    ]
