# Generated by Django 3.1.3 on 2020-12-05 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0019_auto_20201205_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfilter',
            name='type',
        ),
        migrations.AddField(
            model_name='additionalfilter',
            name='type_premise',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='estate_app.typepremise'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 51, 10, 444282)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 11, 51, 10, 459903)),
        ),
    ]
