# Generated by Django 3.1.3 on 2020-12-05 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0023_auto_20201205_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 12, 10, 37, 32798)),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='type_premise',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='estate_app.typepremise'),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 5, 12, 10, 37, 32798)),
        ),
    ]
