# Generated by Django 3.1.3 on 2020-12-07 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0028_auto_20201207_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='top_offer',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 16, 17, 37, 951269)),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 16, 17, 37, 951269)),
        ),
    ]
