# Generated by Django 3.1.3 on 2020-12-09 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0029_auto_20201207_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 10, 15, 41, 88939)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='square_meters',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 10, 15, 41, 90937)),
        ),
    ]
