# Generated by Django 3.1.3 on 2020-12-09 11:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0033_auto_20201209_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 13, 59, 20, 336303)),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='sale_or_rent',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='estate_app.saleorrent'),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 13, 59, 20, 339433)),
        ),
    ]
