# Generated by Django 3.1.3 on 2020-12-09 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0034_auto_20201209_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 14, 0, 34, 442638)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sale_or_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.saleorrent'),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='sale_or_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_app.saleorrent'),
        ),
        migrations.AlterField(
            model_name='lookingfor',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 14, 0, 34, 442638)),
        ),
    ]
