# Generated by Django 3.1.3 on 2020-12-09 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0035_auto_20201209_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 15, 30, 50, 460993)),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='number_rooms',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate_app.numberrooms'),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='sale_or_rent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate_app.saleorrent'),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='sort',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate_app.sortoptions'),
        ),
        migrations.AlterField(
            model_name='additionalfilter',
            name='type_premise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estate_app.typepremise'),
        ),
        migrations.DeleteModel(
            name='LookingFor',
        ),
    ]
