# Generated by Django 3.1.3 on 2020-12-09 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0036_auto_20201209_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 15, 52, 53, 85508)),
        ),
    ]
