# Generated by Django 3.1.3 on 2020-12-09 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0037_auto_20201209_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='comments_reject',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 16, 22, 24, 53363)),
        ),
    ]
