# Generated by Django 3.1.3 on 2020-12-12 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0038_auto_20201209_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalfilter',
            old_name='my_add',
            new_name='my_ad',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 16, 25, 46, 259333)),
        ),
    ]
