# Generated by Django 3.1.3 on 2020-12-12 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0039_auto_20201212_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 20, 29, 6, 629064)),
        ),
    ]
