# Generated by Django 3.1.3 on 2020-12-12 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0041_auto_20201212_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 20, 43, 29, 248705)),
        ),
    ]
