# Generated by Django 3.1.3 on 2021-01-04 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0042_auto_20201212_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfilter',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 11, 23, 15, 75990)),
        ),
    ]
